### PR TITLE
Ingress and egress Network policies for mcg-osd deployer

### PR DESCRIPTION
**Pull request by v-harihar**
Ingress NetworkPolicy - Allows pod to pod communication within namespace(redhat-data-federation), Blocks traffic from outside **redhat-data-federation**. As this is applied to all the pods in the Namespace, default deny ingress networkpolicy is not required

EgressNetworkPolicy - Blocks outgoing traffic and allows only the required external domains

Signed-off-by: Vinayakswami Hariharmath <vharihar@redhat.com>

### CODE REVIEW

**Comment by naveenpaul1** [comment]
@v-harihar could you please resolve lint and test the pipeline

**Review by naveenpaul1 — CHANGES_REQUESTED** [review]
LGTM

**Comment by rexagod** [comment]
Please look into the failing test-suite (adding `egress` to scheme).

**Comment by v-harihar** [comment]
@rexagod 

> Please look into the failing test-suite (adding egress to scheme).

egress is added to schema. I latest failures are not related to this patch.

**Review by naveenpaul1 — APPROVED** [review]
/LGTM

**Pull request merged**
