### PR TITLE
Add test harness for `osde2e`

### PR DESCRIPTION
**Pull request by rexagod**
Adds harness script that will be used to run `osde2e` tests.

Signed-off-by: Pranshu Srivastava <rexagod@gmail.com>

### CODE REVIEW

**Comment by alfonsomthd** [comment]
@rexagod As this is part of the Continous Integration, I would add these files under a "ci/osde2e" folder,
the `hack` folder does nto seem appropriate here...

**Comment by alfonsomthd** [comment]
@rexagod Please add documentation that explains the purpose of this and how to generate this image.

**Comment by naveenpaul1** [comment]
@rexagod can you update the test harness image in managed-tenets repo?

**Pull request closed without merging**
