### PR TITLE
Setup integration test environment

### PR DESCRIPTION
**Pull request by rexagod**
This commit adds initial integration test for `managedmcg_controller`.

### CODE REVIEW

**Review by naveenpaul1 — CHANGES_REQUESTED** [review]
@rexagod the test case looks more like a unit test, can you create valid integration test, If its just a frame work for integration then its fine for me

**Comment by naveenpaul1** [comment]
// @aspandey @v-harihar

**Comment by rexagod** [comment]
Yes this is just a setup @naveenpaul1

**Comment by rexagod** [comment]
Yes it's just a setup. Let's merge this after #12

**Review by naveenpaul1 — APPROVED** [review]
LGTM

**Pull request merged**
