### PR TITLE
reconcile console even if secret error

### PR DESCRIPTION
**Pull request by naveenpaul1**
reconcile console even if the secret is missing

### CODE REVIEW

**Review by rexagod — CHANGES_REQUESTED** [review]
I see this PR is reordering the functions. Was the older order causing some checks to be skipped?

**Comment by naveenpaul1** [comment]
>

**Comment by naveenpaul1** [comment]
@rexagod yes, if SMTP or pagerduty secret is missing console reconcile will not happen and it will affect the addon itself, and alert and monitoring resources should not affect addon itself.

**Pull request merged**
