### PR TITLE
TLS PR follow ups

### PR DESCRIPTION
**Pull request by rexagod**
Allow ClusterRoleBindings to utilize Kustomize for substituting namespaces.

### CODE REVIEW

**Comment by rexagod** [comment]
<details>
<summary>Verified.</summary>

Screenshot from 2022-06-08 00-32-39
Screenshot from 2022-06-08 00-33-03
Screenshot from 2022-06-08 00-34-49
Screenshot from 2022-06-08 00-33-10

</details>

**Review by naveenpaul1 — APPROVED** [review]
LGTM

**Pull request merged**
